### ISSUE TITLE
修改 MANIFESTID 操作，填入steamdb的cookies后提示过期

### ISSUE THREAD

**Issue by ZSkycat** [Jack-Myth/SteamDepotDownloader-GUI#2]
能否提供一个手动输入 MANIFESTID 的操作呢，直接steamdb查询后手动填上

**Comment by ZSkycat** [comment]
另外高级下载中的文件列表应该怎么使用，要求导入一个 txt 文件？

**Comment by ZSkycat** [comment]
=3=
我拉代码下来短路加了个文本框就能用起来了
还有多语言支持，太强了

**Comment by Jack-Myth** [comment]
高级下载里可以输入ManifestID，下载列表是要导入一个txt，里面按行写上要包含的文件名或者正则表达式
